# Generated by Django 5.0.1 on 2024-05-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_dislikes1_remove_user_dislikes2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
