# Generated by Django 5.0.3 on 2024-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/'),
        ),
    ]
